name: Run get coin

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

env:
  STOKEN: ${{ secrets.STOKEN }}

jobs:
  push-random:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Generate RANDOM
        run: openssl rand -hex 8 | md5sum > RANDOM
      - name: commit
        run: |
          git config user.email 1121149616@qq.com
          git config user.name DancingSnow
          git add RANDOM
          git commit -m "update RANDOM" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}

  run-coin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: run-coin
        run: python main.py





